### ISSUE TITLE
Add styles for the recover password page

### ISSUE THREAD

**Issue by AlejandroCuriel** [BC-MAY-21-ROR/proyecto-final-k8-f22-t2-local-e-commerce#64]
# REQUIREMENTS
It is currently required to add new styles to the page that the device delivers by default in the "recover password" section, this page has its own page but does not have the styles (colors and sayings) of our project.

# Acceptance Criteria
List all required acceptance criteria
- [ ] It should have the base colors that are used throughout our project.
- [ ] They must use the existing variables, and if necessary create new variables in case they are needed.
- [ ] This page can normally be seen from the link generated by devise.

**Comment by Jnnifr** [comment]
Puntos estimado: 3
