### ISSUE TITLE
Change and hide functions and messages when the user is not logged in

### ISSUE THREAD

**Issue by AlejandroCuriel** [BC-MAY-21-ROR/proyecto-final-k8-f22-t2-local-e-commerce#66]
# REQUIREMENTS
Change the type of message in the "my account" list when you are not logged in, for example, if you are not logged in it should not show the cart and the notification bell, as well as the list changes to say sign in or sign up. Like any other function

# DESIGN
Provide references to images of the design, how it looks now, and how it should look like.

# Acceptance Criteria
List all required acceptance criteria
- [x] Validate that the removed functions continue to be displayed when the user is logged in.
- [x] Verify that the non-logged-in user cannot perform what a logged-in user can do.
- [x] The messages and functions were changed in case of an unregistered user.

**Comment by Jnnifr** [comment]
Puntos estimados aprox: 1
