### ISSUE TITLE
Add styles for the "post comment" page to the product

### ISSUE THREAD

**Issue by AlejandroCuriel** [BC-MAY-21-ROR/proyecto-final-k8-f22-t2-local-e-commerce#67]
# REQUIREMENTS
Add styles on the comment post page, where the display is more friendly when making the product comment.

# Acceptance Criteria
List all required acceptance criteria
- [ ] The layout of the page respects the color style of the project.
- [ ] They should use the existing variables and, if necessary, create new variables in case they are needed.
- [ ] This page can only be viewed if you are logged in.

**Comment by Jnnifr** [comment]
Puntos estimados aprox: 3
