### ISSUE TITLE
Add layout and styles for the notification page

### ISSUE THREAD

**Issue by AlejandroCuriel** [BC-MAY-21-ROR/proyecto-final-k8-f22-t2-local-e-commerce#68]
# REQUIREMENTS
Add some fixed notifications in case they cannot be obtained from the DB and give them styles for when the corresponding data exists as soon as they are displayed in the appropriate way

# DESIGN
A sample of what it should look like
![Screenshot from 2022-05-16 22-23-53](https://user-images.githubusercontent.com/39254580/168722137-87eea2e0-806c-41d0-92fd-3ac62666b0ce.png)

# Acceptance Criteria
List all required acceptance criteria
- [ ] The layout of the page respects the color style of the project.
- [ ] They should use the existing variables and, if necessary, create new variables in case they are needed.
- [ ] This page can only be viewed if you are logged in.

**Comment by Jnnifr** [comment]
Puntos estimados aprox: 2
