### ISSUE TITLE
Add the layout and styles to show the main information of the same user

### ISSUE THREAD

**Issue by AlejandroCuriel** [BC-MAY-21-ROR/proyecto-final-k8-f22-t2-local-e-commerce#69]
# REQUIREMENTS
The user's information must be retrieved from the database, where it can be displayed on the user's profile page and likewise add a button to edit the said information of the same user desired by him/her.

# DESIGN
![Image](https://user-images.githubusercontent.com/54031790/169419351-0fdd7b72-f4e3-4305-88c1-54febb4e352f.png)

# Acceptance Criteria
List all required acceptance criteria
- [ ] The layout of the page respects the color style of the project.
- [ ] They should use the existing variables and, if necessary, create new variables in case they are needed.
- [ ] This page can only be viewed if you are logged in.

**Comment by Jnnifr** [comment]
Puntos estimados aprox: 2
