### ISSUE TITLE
Add styles to the product purchase order note

### ISSUE THREAD

**Issue by AlejandroCuriel** [BC-MAY-21-ROR/proyecto-final-k8-f22-t2-local-e-commerce#70]
# REQUIREMENTS
When a product is purchased, it throws a note where it can be shown what was purchased and at what time it was purchased, but some styles need to be added to make it more pleasant when viewing the note of said purchase.

# Acceptance Criteria
List all required acceptance criteria
- [ ] The layout of the page respects the color style of the project.
- [ ] They should use the existing variables and, if necessary, create new variables in case they are needed.
- [ ] This page can only be viewed if you are logged in.

**Comment by Jnnifr** [comment]
Puntos estimados aprox: 2
