### ISSUE TITLE
Add the sidebar navigation menu

### ISSUE THREAD

**Issue by AlejandroCuriel** [BC-MAY-21-ROR/proyecto-final-k8-f22-t2-local-e-commerce#71]
# REQUIREMENTS
Add the sidebar navigation menu, this must have the routes, and this will be fixed when navigating between the routes or special features (information, favorites, notifications, purchases, etc) of the user

# DESIGN
Provide references to images of the design
![Screenshot from 2022-05-16 22-48-32](https://user-images.githubusercontent.com/39254580/168724693-b7754b1d-7ae5-424b-bd5a-0cbb0bc812a4.png)

# Acceptance Criteria
List all required acceptance criteria
- [x] All features have their link
- [x] The layout of the page respects the color style of the project.
- [x] They should use the existing variables and, if necessary, create new variables in case they are needed.
- [x] This page can only be viewed if you are logged in.

**Comment by Jnnifr** [comment]
Puntos estimados aprox: 3

**Comment by Jnnifr** [comment]
Puntos estimados aprox: 3

**Comment by Jnnifr** [comment]
Puntos estimados aprox: 3

**Comment by Jnnifr** [comment]
Puntos estimados aprox: 3
